# This is the name of the workflow.
name: Publish Docker image

on:
  push:
    branches: ['main']
#  This is a list of jobs that the workflow will perform
jobs:
  #  name of the job 
  push_to_registry:
    name: Push Docker image to Docker Hub
    #  the operating system that the job will run on.
    runs-on: ubuntu-latest
    steps:
      # tải một bản sao của mã nguồn từ kho lưu trữ và đưa nó vào thư mục làm việc của workflow
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        # This action extracts metadata for a Docker image, including its tags and labels.
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          #  This specifies the Docker image name that the metadata should be extracted for.
          images:  bedan/chubedan

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}